sonar.organization=moncadamario
sonar.projectKey=MoncadaMario_NutriAgenda
sonar.sources=lib
sonar.tests=test
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=lib/data/**,test/**,lib/utils/session_cookie_web.dart